# Permalinks
permalink:           pretty

# Setup
title:               'silviogulizia'
url:                 /
tagline:             writer and geek
paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

# Includes
include:
  - _redirects

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Silvio Gulizia
  url:               https://twitter.com/silviogulizia
  email:             desk@silviogulizia.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/sigul/taunt-fork

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
